package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const activateScript = `# Generated by govenv — do not edit.
export GOVENV=%q
export GOVENV_PROMPT=%q
export GOVENV_GO_ROOT=%q
export _GOVENV_OLD_PATH="$PATH"
if [ -n "$GOVENV_GO_ROOT" ]; then
    export PATH="$GOVENV_GO_ROOT/bin:$GOVENV:$PATH"
else
    export PATH="$GOVENV:$PATH"
fi

govenv-deactivate() {
    export PATH="$_GOVENV_OLD_PATH"
    unset _GOVENV_OLD_PATH GOVENV GOVENV_PROMPT GOVENV_GO_ROOT
    unset -f govenv-deactivate
    echo "govenv: deactivated"
}

echo "govenv: activated $GOVENV_PROMPT"
echo "govenv: to exit, run: govenv-deactivate"
`

func main() {
	// Subcommand dispatch. Each command handles its own -h/--help.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "help", "-h", "--help":
			printHelp(os.Stdout)
			return
		case "list-go":
			if hasHelpFlag(os.Args[2:]) {
				printListGoHelp(os.Stdout)
				return
			}
			listGo()
			return
		case "deactivate":
			if hasHelpFlag(os.Args[2:]) {
				printDeactivateHelp(os.Stdout)
				return
			}
			deactivate()
			return
		}
	}

	var (
		clear    = flag.Bool("clear", false, "delete the contents of the env directory before creating")
		upgrade  = flag.Bool("upgrade", false, "upgrade an existing env (rebuild and reinstall the binary)")
		prompt   = flag.String("prompt", "", "override the prompt prefix shown on activation")
		symlinks = flag.Bool("symlinks", false, "symlink the binary into the env dir instead of copying")
		copies   = flag.Bool("copies", false, "copy the binary into the env dir (default)")
		goVer    = flag.String("go", "", "use a specific Go toolchain installed under ~/sdk/ (e.g. 1.22.3)")
	)
	flag.Usage = func() { printHelp(os.Stderr) }
	flag.Parse()

	if flag.NArg() == 0 {
		flag.Usage()
		os.Exit(1)
	}

	if *symlinks && *copies {
		fmt.Fprintln(os.Stderr, "govenv: --symlinks and --copies are mutually exclusive")
		os.Exit(1)
	}

	envDir := flag.Arg(0)
	absDir, err := filepath.Abs(envDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	goBin := "go"
	goRoot := ""
	if *goVer != "" {
		inst, err := resolveGoVersion(*goVer)
		if err != nil {
			fmt.Fprintln(os.Stderr, "govenv:", err)
			os.Exit(1)
		}
		goBin = inst.GoBin
		goRoot = inst.Root
	}

	// Must be run from a Go module directory
	modName, err := readModuleName("go.mod")
	if err != nil {
		fmt.Fprintln(os.Stderr, "govenv: no go.mod found — run from a Go module directory")
		os.Exit(1)
	}
	binName := filepath.Base(modName)

	if *clear {
		if err := os.RemoveAll(absDir); err != nil {
			fmt.Fprintln(os.Stderr, "govenv: --clear:", err)
			os.Exit(1)
		}
	}

	if !*upgrade {
		if _, err := os.Stat(absDir); err == nil {
			fmt.Fprintf(os.Stderr, "govenv: env already exists at %s (use --clear or --upgrade)\n", absDir)
			os.Exit(1)
		} else if !errors.Is(err, os.ErrNotExist) {
			fmt.Fprintln(os.Stderr, "govenv:", err)
			os.Exit(1)
		}
	}

	if err := os.MkdirAll(absDir, 0755); err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	// Build the binary into the env dir
	binPath := filepath.Join(absDir, binName)
	if err := build(binPath, goBin, *symlinks); err != nil {
		fmt.Fprintln(os.Stderr, "govenv: build failed:", err)
		os.Exit(1)
	}

	// Write activate script
	name := *prompt
	if name == "" {
		name = binName
	}
	script := fmt.Sprintf(activateScript, absDir, name, goRoot)
	if err := os.WriteFile(filepath.Join(absDir, "activate"), []byte(script), 0644); err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	fmt.Printf("govenv: created %s (%s)\n", absDir, binName)
	fmt.Printf("Activate with: source %s/activate\n", envDir)
}

func build(binPath, goBin string, useSymlink bool) error {
	if useSymlink {
		// Build to a temp location, then symlink
		tmp := binPath + ".tmp"
		cmd := exec.Command(goBin, "build", "-o", tmp, ".")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return err
		}
		os.Remove(binPath)
		return os.Symlink(tmp, binPath)
	}

	cmd := exec.Command(goBin, "build", "-o", binPath, ".")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// deactivate prints shell code that tears down an active govenv session.
// It is meant to be eval'd in the calling shell: eval "$(govenv deactivate)".
// Using a subcommand instead of a sourced shell function avoids colliding with
// Python venv's `deactivate` function.
func deactivate() {
	if os.Getenv("GOVENV") == "" {
		fmt.Fprintln(os.Stderr, "govenv: no active env")
		os.Exit(1)
	}
	fmt.Printf("export PATH=%s\n", shellQuote(os.Getenv("_GOVENV_OLD_PATH")))
	fmt.Println("unset _GOVENV_OLD_PATH GOVENV GOVENV_PROMPT GOVENV_GO_ROOT")
	fmt.Println(`echo "govenv: deactivated"`)
}

// shellQuote wraps s in single quotes, safe for POSIX shells even if s
// contains spaces or special characters.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// hasHelpFlag reports whether args contains a help request (-h/--help/help).
func hasHelpFlag(args []string) bool {
	for _, a := range args {
		if a == "-h" || a == "--help" || a == "help" {
			return true
		}
	}
	return false
}

func printHelp(w io.Writer) {
	fmt.Fprint(w, `govenv — per-project Go environments

USAGE
  govenv [options] ENV_DIR     create or manage an env in ENV_DIR
  govenv <command> [args]

COMMANDS
  list-go         list Go toolchains detected under ~/sdk/
  deactivate      print shell code to exit an env (scripting fallback; eval it)
  help            show this help

To exit an active env, run the govenv-deactivate command that 'source activate'
defines in your shell (no eval needed).

OPTIONS
  --clear         delete the env directory before creating it
  --upgrade       rebuild and reinstall the binary into an existing env
  --go VERSION    use a specific Go toolchain under ~/sdk/ (e.g. 1.22.3)
  --prompt NAME   override the prompt prefix shown on activation
  --symlinks      symlink the binary into the env dir instead of copying
  --copies        copy the binary into the env dir (default)

EXAMPLES
  govenv .venv && source .venv/activate   create an env and activate it
  govenv --go 1.22.3 .venv                pin a Go toolchain
  govenv --upgrade .venv                  rebuild after code changes
  govenv-deactivate                       exit the active env

Run 'govenv <command> -h' for command-specific help.
`)
}

func printListGoHelp(w io.Writer) {
	fmt.Fprint(w, `govenv list-go — list detected Go toolchains

Lists Go toolchains found under ~/sdk/, where the Go team's downloader installs
versioned toolchains. govenv detects them but does not install them.

USAGE
  govenv list-go

Install a toolchain so it shows up here:
  go install golang.org/dl/go1.22.3@latest && go1.22.3 download

Use one when creating an env:
  govenv --go 1.22.3 .venv
`)
}

func printDeactivateHelp(w io.Writer) {
	fmt.Fprint(w, `govenv deactivate — print shell code to exit the active env

Normally you don't need this. 'source activate' defines a govenv-deactivate
command in your shell; just run that to exit an env:

  govenv-deactivate

This subcommand exists only as a scripting fallback. A binary cannot modify the
shell that launched it, so it merely prints the restore commands to stdout — you
must eval them in the current shell:

  eval "$(govenv deactivate)"

Exits non-zero if no env is active.
`)
}

func listGo() {
	installs := detectGoInstalls()
	if len(installs) == 0 {
		fmt.Println("govenv: no Go versions found in ~/sdk/.")
		fmt.Println("Install one with: go install golang.org/dl/goX.Y.Z@latest && goX.Y.Z download")
		return
	}
	fmt.Printf("%-10s %s\n", "VERSION", "PATH")
	for _, g := range installs {
		fmt.Printf("%-10s %s\n", g.Version, g.Root)
	}
}

func readModuleName(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("module directive not found")
}
