package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"strings"
)

const activateScript = `# Generated by govenv — do not edit.
export GOVENV=%q
export GOVENV_PROMPT=%q
export GOVENV_GO_ROOT=%q
export _GOVENV_OLD_PATH="$PATH"
if [ -n "$GOVENV_GO_ROOT" ]; then
    export PATH="$GOVENV_GO_ROOT/bin:$GOVENV:$PATH"
else
    export PATH="$GOVENV:$PATH"
fi

govenv-deactivate() {
    export PATH="$_GOVENV_OLD_PATH"
    unset _GOVENV_OLD_PATH GOVENV GOVENV_PROMPT GOVENV_GO_ROOT
    unset -f govenv-deactivate
    echo "govenv: deactivated"
}

echo "govenv: activated $GOVENV_PROMPT"
echo "govenv: to exit, run: govenv-deactivate"
`

func main() {
	// Subcommand dispatch. Each command handles its own -h/--help.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "help", "-h", "--help":
			printHelp(os.Stdout)
			return
		case "version", "-v", "--version", "-version":
			printVersion(os.Stdout)
			return
		case "list-go":
			if hasHelpFlag(os.Args[2:]) {
				printListGoHelp(os.Stdout)
				return
			}
			listGo()
			return
		case "completion":
			shell := ""
			if len(os.Args) > 2 {
				shell = os.Args[2]
			}
			if hasHelpFlag(os.Args[2:]) || shell == "" {
				printCompletionHelp(os.Stderr)
				if shell == "" {
					os.Exit(1)
				}
				return
			}
			if err := printCompletion(os.Stdout, shell); err != nil {
				fmt.Fprintln(os.Stderr, "govenv:", err)
				os.Exit(1)
			}
			return
		case "deactivate":
			// Not a subcommand. Catch it so it isn't treated as an ENV_DIR
			// name (which would create an env called "deactivate").
			fmt.Fprintln(os.Stderr, "govenv: 'deactivate' is not a govenv command.")
			fmt.Fprintln(os.Stderr, "To exit an active env, run: govenv-deactivate")
			fmt.Fprintln(os.Stderr, "(your shell defines it after 'source <ENV_DIR>/activate')")
			os.Exit(1)
		}
	}

	var (
		clear    = flag.Bool("clear", false, "delete the contents of the env directory before creating")
		upgrade  = flag.Bool("upgrade", false, "upgrade an existing env (rebuild and reinstall the binary)")
		prompt   = flag.String("prompt", "", "override the prompt prefix shown on activation")
		symlinks = flag.Bool("symlinks", false, "symlink the binary into the env dir instead of copying")
		copies   = flag.Bool("copies", false, "copy the binary into the env dir (default)")
		goVer    = flag.String("go", "", "use a specific Go toolchain installed under ~/sdk/ (e.g. 1.22.3)")
	)
	flag.Usage = func() { printHelp(os.Stderr) }
	flag.Parse()

	if flag.NArg() == 0 {
		flag.Usage()
		os.Exit(1)
	}

	if *symlinks && *copies {
		fmt.Fprintln(os.Stderr, "govenv: --symlinks and --copies are mutually exclusive")
		os.Exit(1)
	}

	envDir := flag.Arg(0)
	absDir, err := filepath.Abs(envDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	goBin := "go"
	goRoot := ""
	if *goVer != "" {
		inst, err := resolveGoVersion(*goVer)
		if err != nil {
			fmt.Fprintln(os.Stderr, "govenv:", err)
			os.Exit(1)
		}
		goBin = inst.GoBin
		goRoot = inst.Root
	}

	// Must be run from a Go module directory
	modName, err := readModuleName("go.mod")
	if err != nil {
		fmt.Fprintln(os.Stderr, "govenv: no go.mod found — run from a Go module directory")
		os.Exit(1)
	}
	binName := filepath.Base(modName)

	if *clear {
		if err := os.RemoveAll(absDir); err != nil {
			fmt.Fprintln(os.Stderr, "govenv: --clear:", err)
			os.Exit(1)
		}
	}

	if !*upgrade {
		if _, err := os.Stat(absDir); err == nil {
			fmt.Fprintf(os.Stderr, "govenv: env already exists at %s (use --clear or --upgrade)\n", absDir)
			os.Exit(1)
		} else if !errors.Is(err, os.ErrNotExist) {
			fmt.Fprintln(os.Stderr, "govenv:", err)
			os.Exit(1)
		}
	}

	if err := os.MkdirAll(absDir, 0755); err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	// Build the binary into the env dir
	binPath := filepath.Join(absDir, binName)
	if err := build(binPath, goBin, *symlinks); err != nil {
		fmt.Fprintln(os.Stderr, "govenv: build failed:", err)
		os.Exit(1)
	}

	// Write activate script
	name := *prompt
	if name == "" {
		name = binName
	}
	script := fmt.Sprintf(activateScript, absDir, name, goRoot)
	if err := os.WriteFile(filepath.Join(absDir, "activate"), []byte(script), 0644); err != nil {
		fmt.Fprintln(os.Stderr, "govenv:", err)
		os.Exit(1)
	}

	fmt.Printf("govenv: created %s (%s)\n", absDir, binName)
	fmt.Printf("Activate with: source %s/activate\n", envDir)
}

func build(binPath, goBin string, useSymlink bool) error {
	if useSymlink {
		// Build to a temp location, then symlink
		tmp := binPath + ".tmp"
		cmd := exec.Command(goBin, "build", "-o", tmp, ".")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return err
		}
		os.Remove(binPath)
		return os.Symlink(tmp, binPath)
	}

	cmd := exec.Command(goBin, "build", "-o", binPath, ".")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// hasHelpFlag reports whether args contains a help request (-h/--help/help).
func hasHelpFlag(args []string) bool {
	for _, a := range args {
		if a == "-h" || a == "--help" || a == "help" {
			return true
		}
	}
	return false
}

// printVersion reports the module version embedded by the Go toolchain. For
// `go install ...@vX.Y.Z` builds this is the tag; for a local `go build` of a
// git checkout it is "(devel)" plus the VCS revision and commit time.
func printVersion(w io.Writer) {
	version := "unknown"
	var revision, vcsTime string
	if bi, ok := debug.ReadBuildInfo(); ok {
		if bi.Main.Version != "" {
			version = bi.Main.Version
		}
		for _, s := range bi.Settings {
			switch s.Key {
			case "vcs.revision":
				revision = s.Value
			case "vcs.time":
				vcsTime = s.Value
			}
		}
	}
	fmt.Fprintf(w, "govenv %s\n", version)
	if revision != "" {
		short := revision
		if len(short) > 12 {
			short = short[:12]
		}
		if vcsTime != "" {
			fmt.Fprintf(w, "commit %s (%s)\n", short, vcsTime)
		} else {
			fmt.Fprintf(w, "commit %s\n", short)
		}
	}
}

func printCompletion(w io.Writer, shell string) error {
	switch shell {
	case "bash":
		fmt.Fprint(w, bashCompletion)
	case "zsh":
		fmt.Fprint(w, zshCompletion)
	default:
		return fmt.Errorf("unsupported shell %q (supported: bash, zsh)", shell)
	}
	return nil
}

func printCompletionHelp(w io.Writer) {
	fmt.Fprint(w, `govenv completion — print a shell completion script

USAGE
  govenv completion <bash|zsh>

Completes govenv subcommands, flags, env directories, and --go toolchain
versions. The govenv-deactivate command is completed by your shell's normal
command-name completion once an env is active (try: govenv-<Tab>).

bash — add to ~/.bashrc:
  source <(govenv completion bash)

zsh — install once onto your fpath, then restart your shell:
  govenv completion zsh > "${fpath[1]}/_govenv"
  # or, for the current shell only:
  source <(govenv completion zsh)
`)
}

// bashCompletion completes govenv for bash. (govenv-deactivate is handled by
// bash's default command-name completion when the function is defined.)
const bashCompletion = `# govenv bash completion
_govenv() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ "$prev" == "--go" ]]; then
        COMPREPLY=( $(compgen -W "$(govenv list-go 2>/dev/null | awk 'NR>1 {print $1}')" -- "$cur") )
        return
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--clear --upgrade --go --prompt --symlinks --copies --help --version" -- "$cur") )
        return
    fi

    if [[ "$COMP_CWORD" -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "list-go version completion help" -- "$cur") )
        COMPREPLY+=( $(compgen -d -- "$cur") )
        return
    fi

    COMPREPLY=( $(compgen -d -- "$cur") )
}
complete -F _govenv govenv
`

// zshCompletion completes govenv for zsh. (govenv-deactivate is handled by
// zsh's default command-name completion when the function is defined.)
const zshCompletion = `#compdef govenv
_govenv_goversions() {
    local -a vers
    vers=(${(f)"$(govenv list-go 2>/dev/null | awk 'NR>1 {print $1}')"})
    compadd -a vers
}
_govenv() {
    local -a cmds
    cmds=(
        'list-go:list Go toolchains detected under ~/sdk/'
        'version:print the govenv version'
        'completion:print a shell completion script'
        'help:show help'
    )
    local state
    _arguments -s \
        '--clear[delete the env dir before creating it]' \
        '--upgrade[rebuild and reinstall into an existing env]' \
        '--go[use a Go toolchain under ~/sdk/]:version:_govenv_goversions' \
        '--prompt[override the activation prompt]:name:' \
        '--symlinks[symlink the binary into the env dir]' \
        '--copies[copy the binary into the env dir]' \
        '--help[show help]' \
        '--version[print the govenv version]' \
        '1:command or env dir:->first' \
        '*::arg:_files -/'

    if [[ "$state" == first ]]; then
        _describe -t commands 'govenv command' cmds
        _files -/
    fi
}
compdef _govenv govenv
`

func printHelp(w io.Writer) {
	fmt.Fprint(w, `govenv — per-project Go environments

USAGE
  govenv [options] ENV_DIR     create or manage an env in ENV_DIR
  govenv <command> [args]

ACTIVATING AN ENV
  source <ENV_DIR>/activate    enter the env
  govenv-deactivate            exit the env

COMMANDS
  list-go         list Go toolchains detected under ~/sdk/
  version         print the govenv version (also -v / --version)
  completion      print a shell completion script (bash or zsh)
  help            show this help

OPTIONS
  --clear         delete the env directory before creating it
  --upgrade       rebuild and reinstall the binary into an existing env
  --go VERSION    use a specific Go toolchain under ~/sdk/ (e.g. 1.22.3)
  --prompt NAME   override the prompt prefix shown on activation
  --symlinks      symlink the binary into the env dir instead of copying
  --copies        copy the binary into the env dir (default)

EXAMPLES
  govenv .venv && source .venv/activate   create an env and activate it
  govenv-deactivate                       exit the active env
  govenv --go 1.22.3 .venv                pin a Go toolchain
  govenv --upgrade .venv                  rebuild after code changes

Run 'govenv <command> -h' for command-specific help.
`)
}

func printListGoHelp(w io.Writer) {
	fmt.Fprint(w, `govenv list-go — list detected Go toolchains

Lists Go toolchains found under ~/sdk/, where the Go team's downloader installs
versioned toolchains. govenv detects them but does not install them.

USAGE
  govenv list-go

Install a toolchain so it shows up here:
  go install golang.org/dl/go1.22.3@latest && go1.22.3 download

Use one when creating an env:
  govenv --go 1.22.3 .venv
`)
}

func listGo() {
	installs := detectGoInstalls()
	if len(installs) == 0 {
		fmt.Println("govenv: no Go versions found in ~/sdk/.")
		fmt.Println("Install one with: go install golang.org/dl/goX.Y.Z@latest && goX.Y.Z download")
		return
	}
	fmt.Printf("%-10s %s\n", "VERSION", "PATH")
	for _, g := range installs {
		fmt.Printf("%-10s %s\n", g.Version, g.Root)
	}
}

func readModuleName(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("module directive not found")
}
